# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12-WKJria1RhdUrtBh65AHp7TyM7F9b8k
"""

from RPS_game import play, quincy, abbey, kris, mrugesh
from RPS import player

print("Testing against Quincy")
play(player, quincy, 1000)

print("\nTesting against Abbey")
play(player, abbey, 1000)

print("\nTesting against Kris")
play(player, kris, 1000)

print("\nTesting against Mrugesh")
play(player, mrugesh, 1000)

